version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install node_modules
                command: yarn
            - run:
                name: Build
                command: yarn build
            - run:
                name: Deploy to Firebase
                command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
